### ISSUE TITLE
Detection of corrupted video/img files crashes application

### ISSUE THREAD

**Issue by jibi4** [OpenTrafficCam/OTVision#101]
**TODO:**

- [ ] handling error when trying to detect corrupt video/img (OTVision.detect.yolo.py)
- [ ] raising custom exception when encountering corrupt video/img
- [ ] handling error in gui

**Comment by martinbaerwolff** [comment]
@randy-seng is this still relevant?
