### ISSUE TITLE
Reorganisation of project structure needed in order to fix import errors

### ISSUE THREAD

**Issue by randy-seng** [OpenTrafficCam/OTVision#110]
Reorganisation of project structure is needed in order to fix import errors and to lay a good foundation of good import practice for future development:

## TODO:
- [x] Replace implicit relative imports with absolute imports or explicit relative imports
- [x] Move .bat files in root project directory. Script files should not reside in the source folder `OTVision`
- [x] Move python files that are to be executed up to the root project directory. This concerns the files `convert.py, detect.py, gui.py, track.py, transform.py, video_player.py` in `OTVision`

**Comment by jibi4** [comment]
A good read on imports in python:
https://realpython.com/absolute-vs-relative-python-imports/
https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html

**Comment by martinbaerwolff** [comment]
> Move python files that are to be executed up to the root project directory.

Why is that? Shouldnt they be in the root of the package (OTVision/OTVision) instead of the root of the project directory? I guess later via PYPI only the files inside the package will be distributed...

**Comment by randy-seng** [comment]
If we look at the files under discussion, in our case `convert.py`, `detect.py`, and `gui.py`, we can see that we are only calling their `.main()` methods with user defined parameters.

#### convert.py
```python
from pathlib import Path
from OTVision.convert import main as convert


if __name__ == "__main__":
    convert(
        str(
            Path(__file__).parents[1]
            / r"tests/data/testvideo_FR20_2020-02-20_12-00-00.h264"
        )
    )
```

#### detect.py
```python
from pathlib import Path

from OTVision import detect

if __name__ == "__main__":
    test_path = Path(__file__).parents[0] / "tests" / "data"
    test_path = str(test_path)
    det_config = {
        "weights": "yolov5s",
        "conf": 0.25,
        "iou": 0.45,
        "size": 640,
        "chunksize": 5,
        "normalized": False,
        "ot_labels_enabled": True,
    }
    detect(test_path, [".mp4", ".jpeg", ".jpg"], **det_config)
```

#### gui.py
```python
from OTVision import gui

# TODO: Add real gui window for OTVision

if __name__ == "__main__":
    gui.main()

```
What I did was editing the `__init__.py` to define an "interface", e.g.:

OTVision __init__.py:

```python
# TODO: Might need to change this
from .detect.detect import main as detect
from .track.track import main as track
from .convert.convert import main as convert
from .gui import __main__ as gui
from .gui.transform_view import main
```

So, now we are able to import and call OTVision as a package, e.g.:

```python
import OTVision

if __name__ == "__main__":
    path_to_video = "path/to/video.h264"
    OTVision.convert(path_to_video)
    
```

I advocate for this approach as these methods should be called with user defined  instead of pre-defined parameters.

Now thinking about it, I think it would be best to remove the scripts in the project directory completely. Instead we could additionally make them executable over the command line as CLI. 

> > Move python files that are to be executed up to the root project directory.
> 
> Why is that? Shouldnt they be in the root of the package (OTVision/OTVision) instead of the root of the project directory? I guess later via PYPI only the files inside the package will be distributed...

**Comment by martinbaerwolff** [comment]
Yes, I agree tp remove them entirely. I wrote them for testing purposes in the first place. Testing should happen straight from the test modules (I have this on my schedule for february). For production the functions in the subpackages can be run via gui and via external API scripts, that should not be part of the package. And for the future I could also think of a CLI using e.g. argparse - but I assume that we ourselves prefer external scripts for using OTVision API, so maybe this is not urgent  to have CLI?

**Comment by martinbaerwolff** [comment]
I am not sure if I understand correctly: Do we need argparse, as the gui is typically run without arguments? Couldnt one start the Gui from command line with e.g. `python -m OTVision.view`... Also, I prepared  a `.bat` file for starting the gui on windows. Maybe we should also prepare a `.command` file for mac users and a `.sh` file for linux users?

**Comment by randy-seng** [comment]
Yes, you are correct sorry! We are able to start the gui with python -m!
